let sha256_iocs = dynamic(["52d07b3ef0c5f27d082551d51027de452682e1fbd5bb38a897ea4b31bd387523","80fdde0dafa450ae33937ccef752b46666da567926b2f39b37e02e77f9d6a92e","05bbeea42f481a3dd1b3f670aba481f7c5c8e897ef321d65188317be5a65a4d7","70fc6cba3c2021889fb4093d0221dc6925818666df25718a630c562cac18da31"]);
let sha1_iocs = dynamic(["00aff1a72c5d5635ab36ce2eb370718a7f0557a0","761ccb15af1c3fe6e4365ddf65578966e4c84fc9","ad4afe86a835bb2f7768862d358ebd8324c05902","00e1cc0fb1355c196c069791a02b4a5f3b57ae94"]);
let md5_iocs = dynamic(["40a75f87f1e52c33df9ca733aaf8ebbb","ae77f1834ccde53258bc27a779102af2","aade06ec611d69f1553035f22356ccf4","f16f507a8ed515663a4f07050cd97a74"]);
let domain_iocs = dynamic(["indiatodays.org","theprints.org","officialinfo.org"]);
let url_iocs = dynamic(["f005.backblazeb2.com/file/clients-easy/driverinstaller.zip","clients-easy.s3.us-east-005.backblazeb2.com/automata-20.zip"]);
let FileHashHits = DeviceFileEvents
| where SHA256 in (sha256_iocs) or SHA1 in (sha1_iocs) or MD5 in (md5_iocs)
| extend MatchType = case(SHA256 in (sha256_iocs), "SHA256", SHA1 in (sha1_iocs), "SHA1", MD5 in (md5_iocs), "MD5", "Unknown"),
         MatchValue = case(SHA256 in (sha256_iocs), SHA256, SHA1 in (sha1_iocs), SHA1, MD5 in (md5_iocs), MD5, "")
| project TimeGenerated, DeviceName, ActionType, FileName, FolderPath, MatchType, MatchValue, ReportId;
let NetworkHits = DeviceNetworkEvents
| where (isnotempty(RemoteUrl) and RemoteUrl has_any (domain_iocs)) or (isnotempty(RemoteUrl) and RemoteUrl has_any (url_iocs))
| extend MatchType = "NetworkIndicator",
         MatchValue = RemoteUrl
| project TimeGenerated, DeviceName, ActionType = "NetworkConnection", FileName = "", FolderPath = "", MatchType, MatchValue, ReportId;
FileHashHits
| union NetworkHits