let LegitAdminTools = dynamic(["ntdsutil.exe", "dsdbutil.exe", "wbadmin.exe", "esentutl.exe", "MsMpEng.exe"]);
let SamRegSave = DeviceProcessEvents
| where FileName =~ "reg.exe"
| where ProcessCommandLine has "save" and ProcessCommandLine has "HKLM\\SAM"
| where InitiatingProcessFileName !in~ (LegitAdminTools)
| project TimeGenerated, DeviceName, AccountName, FileName, ProcessCommandLine, InitiatingProcessFileName, InitiatingProcessCommandLine;
let NtdsProcAccess = DeviceProcessEvents
| where ProcessCommandLine has "ntds.dit"
| where FileName !in~ (LegitAdminTools) and InitiatingProcessFileName !in~ (LegitAdminTools)
| project TimeGenerated, DeviceName, AccountName, FileName, ProcessCommandLine, InitiatingProcessFileName, InitiatingProcessCommandLine;
let NtdsFileAccess = DeviceFileEvents
| where FolderPath endswith @"\Windows\NTDS\ntds.dit"
| where ActionType in ("FileCreated", "FileModified", "FileRenamed")
| where InitiatingProcessFileName !in~ (LegitAdminTools) and InitiatingProcessFileName !~ "lsass.exe"
| project TimeGenerated, DeviceName, AccountName=RequestAccountName, FileName, ProcessCommandLine=InitiatingProcessCommandLine, InitiatingProcessFileName, InitiatingProcessCommandLine;
union SamRegSave, NtdsProcAccess, NtdsFileAccess
| sort by TimeGenerated desc