let KothamineHashes = dynamic(["ec4219a7ecf132c29080fbb20e4ab410c57faa85aeed7acade1eb15d905a6ee0","74eca3973ad72a6ddc9397aff8250d9ee287211fc9a055d5ee290d01cf76a70c"]);
let FileHashHits = DeviceFileEvents
| where SHA256 in~ (KothamineHashes)
| project Timestamp, DeviceId, DeviceName, ActionType, FileName, FolderPath, SHA256, MatchType = "FileHash";
let ProcessHashHits = DeviceProcessEvents
| where SHA256 in~ (KothamineHashes) or InitiatingProcessSHA256 in~ (KothamineHashes)
| project Timestamp, DeviceId, DeviceName, ActionType, FileName, FolderPath, SHA256, MatchType = "ProcessHash";
let NetworkUrlHits = DeviceNetworkEvents
| where ActionType == "ConnectionSuccess"
| where RemoteUrl matches regex @"(?i)^https?://(www\.)?github\.com/cphc811-ui(/|$)"
| project Timestamp, DeviceId, DeviceName, ActionType, RemoteUrl, RemoteIP, InitiatingProcessFileName, MatchType = "MaliciousGithubURL";
union FileHashHits, ProcessHashHits, NetworkUrlHits
| sort by Timestamp desc