// Reference: https://detections.ai/inspirations/01a038d3-353b-751f-96a4-fe737792705c
let ProcessEvents = DeviceProcessEvents
| where FileName =~ "ERAAgent.exe"
| where ProcessCommandLine has_any ("\\pipe\\mojo", "\\pipe\\mojo_pipe", "\\pipe\\spoolss");
let NetworkEvents = DeviceNetworkEvents
| where InitiatingProcessFileName =~ "ERAAgent.exe";
let UnionEvents = DeviceEvents
| where ActionType has "CreateNamedPipe"
| where InitiatingProcessFileName =~ "ERAAgent.exe"
| where AdditionalFields has_any ("mojo", "mojo_pipe", "spoolss")
| where AdditionalFields has_any ("Everyone", "Anonymous Logon", "WD", "AN")
| project TimeGenerated, DeviceName, DeviceId, FileName=InitiatingProcessFileName, ProcessCommandLine=tostring(AdditionalFields), RemoteIP="", RemoteUrl="", InitiatingProcessAccountName=AccountName;
ProcessEvents
| join kind=inner (NetworkEvents) on DeviceId
| where ProcessCommandLine matches regex @"(?i)(user(name)?|pass(word)?)=\S+"
| project TimeGenerated, DeviceName, DeviceId, FileName, ProcessCommandLine, RemoteIP, RemoteUrl, InitiatingProcessAccountName
| union (UnionEvents)