DeviceFileEvents
| where FileName =~ "crond"
| where FolderPath has "/usr/bin" or FolderPath has "/usr/sbin"
| where ActionType in ("FileCreated", "FileModified", "FileRenamed")
| join kind=inner (
    DeviceFileEvents
    | where FileName =~ "ssh"
    | where FolderPath == "/usr/bin/ssh"
    | project SshCreationTime = TimeGenerated, DeviceId, SshLastFileHash = SHA256
) on DeviceId
| where TimeGenerated between ((SshCreationTime - 2s) .. (SshCreationTime + 2s))
| project TimeGenerated, DeviceId, FileName, FolderPath, SHA256, SshCreationTime, ActionType
| summarize arg_max(TimeGenerated, *) by DeviceId, FolderPath